[project]
name = "ExpoSeq"
version = "4.4.3"
description = "A pacakge which provides various ways to analyze NGS data from phage display campaigns"
authors = [
    {name = "Nils Hofmann", email = "nilhof01@gmail.com"},
]
dependencies = [
    "PyQT6",
    "biopython==1.80",
    "editdistance==0.6.2",
    "logomaker==0.8",
    "markdown",
    "matplotlib==3.7.3",
    "networkx==3.1",
    "numpy==1.23.5",
    "openpyxl",
    "pandas==1.5.3",
    "pandasai==1.3.3",
    "python-louvain==0.16",
    "scikit-learn>=1.2.1",
    "scipy==1.11.4",
    "seaborn==0.12.2",
    "sentencepiece==0.1.99",
    "sgt==2.0.3",
    "squarify==0.4.3",
    "tabulate==0.9.0",
    "torch==2.1.0",
    "transformers==4.34.1",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "LICENCE"}

[project.urls]
Homepage = "https://github.com/nilshof01/ExpoSeq"
[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pdm]
package-type = "library"
package-dir = "src"


[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.1.2",
]

[tool.pdm.scripts]
test = "python -m pytest -s src/ExpoSeq/software_tests/tests"
test_new = "python -m pytest -s src/ExpoSeq/software_tests/test_new"
